---
stages:
  - update
  - lint
  - test
  - security
  - lsif
  - publish
  - deploy

include:
  - .gitlab/ci/deploy/gitlab-pages-typedoc.gitlab-ci.yml
  - .gitlab/ci/lint/eslint.gitlab-ci.yml
  - .gitlab/ci/lint/gitlab-ci-lint.gitlab-ci.yml
  - .gitlab/ci/lint/prettier.gitlab-ci.yml
  - .gitlab/ci/lint/shellcheck.gitlab-ci.yml
  - .gitlab/ci/lint/yamllint.gitlab-ci.yml
  - .gitlab/ci/lsif/typescript.gitlab-ci.yml
  - .gitlab/ci/publish/npmjs.gitlab-ci.yml
  - .gitlab/ci/test/jest.gitlab-ci.yml
  - .gitlab/ci/update/project.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

dependency_scanning:
  stage: security
  needs: []

license_scanning:
  stage: security
  needs: []

sast:
  stage: security
  needs: []

.secret-analyzer:
  stage: security
  needs: []
