---
stages:
  - update
  - test
  - publish

include:
  - remote: https://gitlab.com/megabyte-space/ci/gitlab-ci-templates/-/raw/master/npm-test.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-space/ci/gitlab-ci-templates/-/raw/master/npmjs-publish.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-space/ci/gitlab-ci-templates/-/raw/master/update.gitlab-ci.yml
