---
version: '3'

output: prefixed

vars:
  REPOSITORY_SUBTYPE: cli
  REPOSITORY_TYPE: npm

includes:
  common: ./.common/taskfiles-cli/Taskfile-common.yml
  npm: ./.common/taskfiles-cli/Taskfile-npm.yml
  fix: ./.common/taskfiles-cli/Taskfile-fix.yml
  lint: ./.common/taskfiles-cli/Taskfile-lint.yml
  software: ./.common/taskfiles-cli/Taskfile-{{OS}}.yml
